linters-settings:
    gci:
        sections:
            - standard
            - default
            - prefix(github.com/messikiller/afero-oss)

linters:
    disable-all: true
    enable:
        - gci
        - gofmt
        - gofumpt
        - staticcheck
