version: "2"
linters:
  default: none
  enable:
    - staticcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/messikiller/afero-oss)
    gofumt:
      module-path: github.com/messikiller/afero-oss
    goimports:
      local-prefixes:
          - github.com/messikiller/afero-oss
    golines:
      max-len: 200
      tab-len: 4
      shorten-comments: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
